DROP TABLE EMPLOYE CASCADE CONSTRAINTS;
DROP TABLE CLIENT CASCADE CONSTRAINTS;
DROP TABLE MARQUE CASCADE CONSTRAINTS;
DROP TABLE MODELE CASCADE CONSTRAINTS;
DROP TABLE VEHICULE CASCADE CONSTRAINTS;
DROP TABLE INTERVENTIONS CASCADE CONSTRAINTS;
DROP TABLE INTERVENANT CASCADE CONSTRAINTS;
DROP TABLE TABLEERREURS CASCADE CONSTRAINTS;