SET ECHO ON;
SET WRAP OFF;
SET PAGESIZE 50000;
SPOOL tp1output.log append;

/** partie 2 **/

/** call to create_tables.sql **/
@../../TP0/create_tables.sql;

/** 5 **/
ALTER TABLE EMPLOYE ADD DATEINSTALLATION DATE NULL;

/** 6 **/
AlTER TABLE EMPLOYE MODIFY CATEGORIE NOT NULL ;
AlTER TABLE EMPLOYE MODIFY SALAIRE NOT NULL ;

/** 7 **/
ALTER TABLE EMPLOYE MODIFY PRENOMEMP VARCHAR2(50);
ALTER TABLE EMPLOYE MODIFY PRENOMEMP VARCHAR2(20);

/** 8 **/
ALTER TABLE EMPLOYE DROP COLUMN DATEINSTALLATION;
SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CLIENT';

/** 9 **/
ALTER TABLE CLIENT RENAME COLUMN ADRESSE TO ADRESSECLIENT;
SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CLIENT';

/** 10 **/
ALTER TABLE INTERVENTIONS ADD CONSTRAINT CHK_DATEINTERV CHECK (DATEDEBINTERV < DATEFININTERV);


/** PARTIE 3 **/
/** 11 **/

/** call to insert_data.sql**/
@../../TP0/insert_data.sql;

/* LES PROBLEMES */
/* VU L'AJOUT D'UNE COLONNE PUIS LA SUPPRESSION D'UNE AUTRE COLONNE DANS LA TABLE
EMPLOYE IL Y'A UN PROBLEME DE CORRESPONDENCE ENTRE LES ATTRIBUTS ET VALEURES

LE CLIENT N 23 NE PEUT PAS ETRE NEE LI MOIS : 13 CAR INEXISTANT

LE VEHICULE 77 N'EXISTE PAS D'OU LA VIOLATION D'INTEGRITEE FK_INTERVENTIONS_VEHICULE

cannot insert NULL into ("DBAINTERVENTION"."EMPLOYE"."CATEGORIE")

L'EMPLOYE 88 N'EXISTE PAS D'OU LA VIOLATION D'INTEGRITEE FK_INTERVENANT_EMPLOYE
*/

/** 12 **/
/*
il faut modifier le salaire de l'employé en ajoutant 5000 au salaire actuelle
*/
UPDATE EMPLOYE SET SALAIRE = SALAIRE + 5000 WHERE PRENOMEMP = 'badi' AND NOMEMP = 'hatem'

/** 13 **/
/*desactiver la contrainte*/
ALTER TABLE INTERVENTIONS DISABLE CONSTRAINT CHK_DATEINTERV;

/*modification*/
UPDATE INTERVENTIONS SET DATEDEBINTERV =  DATEDEBINTERV + 5
WHERE EXTRACT(MONTH FROM DATEDEBINTERV) = 2 OR EXTRACT(MONTH FROM DATEFININTERV) = 2 ;

/*réactivation de la contrainte*/
CREATE TABLE TABLEERREURS (ADRESSE ROWID, UTILISATEUR VARCHAR2(30), NOMTABLE VARCHAR2(30), NOMCONTRAINTE
VARCHAR2(30));
ALTER TABLE INTERVENTIONS ENABLE CONSTRAINT CHK_DATEINTERV EXCEPTIONS INTO TABLEERREURS;

/** On peut pas réactiver la contrainte à cause de violation par queluqes lignes **/

SELECT * FROM INTERVENTIONS WHERE DATEDEBINTERV >= DATEFININTERV;

SELECT * FROM TABLEERREURS;

/** 14 **/
DELETE VEHICULE WHERE NUMMODELE IN (SELECT NUMMODELE FROM MODELE WHERE MODELE = 'série 5');
/** le problème renconté c'est la violation de la clé étrangère de la relation INTERVENTIONS **/

/** 15 **/
SELECT MARQUE , MODELE FROM MARQUE MA, MODELE MO WHERE MA.NUMMARQUE = MO.NUMMARQUE;

/** 16 **/
SELECT V.* FROM VEHICULE V, INTERVENTIONS I WHERE I.NUMVEHICULE = V.NUMVEHICULE;

/** 17 **/
SELECT AVG(DATEFININTERV - DATEDEBINTERV) AS DUREE_MOYENNE FROM INTERVENTIONS;

/** 18 **/
SELECT NUMVEHICULE, SUM(COUTINTERV) FROM INTERVENTIONS GROUP BY NUMVEHICULE HAVING SUM(COUTINTERV) > 30000;

SPOOL OFF;
