
/**CREATE TABLES**/

CREATE TABLE CLIENT
(
NUMCLIENT INTEGER,
CIV VARCHAR2(40),
PRENOMCLIENT VARCHAR2(40),
NOMCLIENT VARCHAR2(40),
DATENAISSANCE DATE,
ADRESSE VARCHAR2(100),
TELPROF VARCHAR2(40),
TELPRIV VARCHAR2(40),
FAX VARCHAR2(40),
CONSTRAINT PK_CLIENT PRIMARY KEY (NUMCLIENT)
);

CREATE TABLE EMPLOYE
(
NUMEMPLOYE INTEGER,
PRENOMEMP VARCHAR2(40),
NOMEMP VARCHAR2(40),
CATEGORIE VARCHAR2(40),
SALAIRE REAL,
CONSTRAINT PK_EMPLOYE PRIMARY KEY (NUMEMPLOYE),
CONSTRAINT CH_EMPLOYE CHECK (CATEGORIE IN ('MECANICIEN' , 'ASSISTANT'))
);

CREATE TABLE MARQUE (
NUMMARQUE INTEGER,
MARQUE VARCHAR2(40),
PAYS VARCHAR2(40),
CONSTRAINT PK_MARQUE PRIMARY KEY (NUMMARQUE)
);

CREATE TABLE MODELE (
NUMMODELE INTEGER,
NUMMARQUE INTEGER,
MODELE VARCHAR2(40),
CONSTRAINT PK_MODELE PRIMARY KEY (NUMMODELE),
CONSTRAINT FK_MODELE_MARQUE FOREIGN KEY (NUMMARQUE) REFERENCES MARQUE(NUMMARQUE)
);

CREATE TABLE VEHICULE (
NUMVEHICULE INTEGER,
NUMCLIENT INTEGER,
NUMMODELE INTEGER,
NUMIMMAT INTEGER,
ANNEE VARCHAR2(4),
CONSTRAINT PK_VEHICULE PRIMARY KEY (NUMVEHICULE),
CONSTRAINT FK_VEHICULE_CLIENT FOREIGN KEY (NUMCLIENT) REFERENCES CLIENT(NUMCLIENT),
CONSTRAINT FK_VEHICULE_MODELE FOREIGN KEY (NUMMODELE) REFERENCES MODELE(NUMMODELE)
);

CREATE TABLE INTERVENTIONS (
NUMINTERVENTION INTEGER,
NUMVEHICULE INTEGER,
TYPEINTERVENTION VARCHAR2(40),
DATEDEBINTERV DATE,
DATEFININTERV DATE,
COUTINTERV REAL,
CONSTRAINT PK_INTERVENTIONS PRIMARY KEY (NUMINTERVENTION),
CONSTRAINT FK_INTERVENTIONS_VEHICULE FOREIGN KEY (NUMVEHICULE) REFERENCES VEHICULE(NUMVEHICULE)
);

CREATE TABLE INTERVENANT
(
NUMINTERVENTION INTEGER,
NUMEMPLOYE INTEGER,
DATEDEBUT DATE,
DATEFIN DATE,
CONSTRAINT PK_INTERVENANT PRIMARY KEY (NUMINTERVENTION, NUMEMPLOYE),
CONSTRAINT FK_INTERVENANT_EMPLOYE FOREIGN KEY (NUMEMPLOYE)REFERENCES EMPLOYE,
CONSTRAINT FK_INTERVENANT_INTERVENTIONS FOREIGN KEY (NUMINTERVENTION) REFERENCES INTERVENTIONS
);
